### ISSUE TITLE
a new processor class: `Explainer`

### ISSUE THREAD

**Issue by eubinean** [eubinean/politely#33]
## What?

What do you really want?
1. Should show explanations for why you should use 1/2/3.
2. Should explain which rule was applied for:
  1. apply_honorifics
  2. apply_abbreviations
  3. apply_irregulars

That should be it?

## To-do's
- [x] cover more cases 
- [x] provide explanation for using 1/2/3  
- [x] an `Explainer` class
